routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::get('/', function () { return view('welcome'); });
Route::get('/home', 'HomeController@index')->name('home');

//Institution
Route::prefix('institution')->group(function () {

    Route::get('/', 'Institution\InstitutionController@index')->name('institution');
    Route::get('/report', 'Institution\InstitutionController@report')->name('institution.reports');

    Route::resource('course', 'Institution\CourseController')->parameters(['course' => 'url']);
    
    Route::get('/{url}/{class}', 'Institution\ClassesController@show')->name('classes.show');
    Route::get('/{url}/classes/create', 'Institution\ClassesController@create')->name('classes.create');
    Route::post('/{url}/classes/create', 'Institution\ClassesController@store')->name('classes.store');

    Route::get('/{url}/{class}/student/create', 'Institution\StudentController@create')->name('student.create');
    Route::post('/{url}/{class}/student/create', 'Institution\StudentController@store')->name('student.store');
    Route::get('/{url}/{class}/{student}/certify', 'Institution\StudentController@certify')->name('student.certify');

});

resources/views/courses/create.blade.php
@extends('layouts.institution')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <div class="header mt-md-5">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="header-pretitle">Novo Curso</h6>
                            <h1 class="header-title">Adicionar novo curso</h1>
                        </div>
                    </div>
                </div>
            </div>

            <form class="mb-4" action="{{ route('course.store') }}" method="post">
                @csrf

                <div class="form-group">
                    <label>Nome do curso</label>
                    <input type="text" class="form-control" name="name">
                </div>

                <div class="form-group">
                    <label>Nome do coordernador</label>
                    <input type="text" class="form-control" name="coordinator">
                </div>

                <div class="form-group">
                    <label class="mb-1">Descrição do curso</label>
                    <small class="form-text text-muted">Escreve uma breve descrição sobre o curso:</small>
                    <textarea class="form-control" name="description"></textarea>
                </div>

                <hr class="mt-5 mb-5">

                <div class="row align-items-center">
                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label class="mb-1">Padrão MEC</label>
                            <small class="form-text text-muted">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </small>
                            <div class="custom-control custom-switch">
                                <input type="checkbox" class="custom-control-input" name="mec_standard" id="mecInput">
                                <label class="custom-control-label gc-pointer" for="mecInput"></label>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="card bg-light border">
                            <div class="card-body">
                                <h4 class="mb-2"><i class="fe fe-alert-triangle"></i> Aviso</h4>
                                <p class="small text-muted mb-0">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="mb-5">

                <button class="btn btn-block btn-primary">
                    Adicionar curso
                </button>
                <a href="{{ route('course.index') }}" class="btn btn-block btn-link text-muted">
                    Voltar para a página de cursos
                </a>
            </form>

        </div>
    </div>
</div>

@endsection

resources/views/courses/edit.blade.php
@extends('layouts.institution')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-lg-10 col-xl-8">
            <div class="header mt-md-5">
                <div class="header-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="header-pretitle">Editar Curso</h6>
                            <h1 class="header-title">Editar {{$course->name}}</h1>
                        </div>
                    </div>
                </div>
            </div>

            <form class="mb-4" action="{{ route('course.update', ['id' => $course->id]) }}" method="post">
                @csrf
                {{ method_field('PUT') }}

                <div class="form-group">
                    <label>Nome do curso</label>
                    <input type="text" class="form-control" name="name" value="{{$course->name}}">
                </div>

                <div class="form-group">
                    <label>Nome do coordernador</label>
                    <input type="text" class="form-control" name="coordinator" value="{{$course->coordinator}}">
                </div>

                <div class="form-group">
                    <label class="mb-1">Descrição do curso</label>
                    <small class="form-text text-muted">Escreve uma breve descrição sobre o curso:</small>
                    <textarea class="form-control" name="description">{{$course->description}}</textarea>
                </div>

                <div class="row">
                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>Data de início</label>
                            <input type="text" class="form-control flatpickr-input" name="start_date" data-toggle="flatpickr" readonly="readonly" placeholder="Clique para selecionar a data" value="{{$course->start_date}}">
                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label>Data de conclusão</label>
                            <input type="text" class="form-control flatpickr-input" name="closing_date" data-toggle="flatpickr" readonly="readonly" placeholder="Clique para selecionar a data" value="{{$course->closing_date}}">
                        </div>
                    </div>
                </div>

                <hr class="mt-5 mb-5">

                <div class="row align-items-center">
                    <div class="col-12 col-md-6">
                        <div class="form-group">
                            <label class="mb-1">Padrão MEC</label>
                            <small class="form-text text-muted">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            </small>
                            <div class="custom-control custom-switch">
                                <input type="checkbox" class="custom-control-input" name="mec_standard" id="mecInput"
                                @if($course->mec_standard == true) checked @endif>
                                <label class="custom-control-label gc-pointer" for="mecInput"></label>
                            </div>
                        </div>
                    </div>

                    <div class="col-12 col-md-6">
                        <div class="card bg-light border">
                            <div class="card-body">
                                <h4 class="mb-2"><i class="fe fe-alert-triangle"></i> Aviso</h4>
                                <p class="small text-muted mb-0">
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <hr class="mt-5 mb-5">

                <button class="btn btn-block btn-primary">
                    Editar informações
                </button>
                <a href="{{ route('course.index') }}" class="btn btn-block btn-link text-muted">
                    Voltar para a página de cursos
                </a>
            </form>

        </div>
    </div>
</div>

@endsection

resources/views/courses/header.blade.php
<div class="header">
    <div class="container">
        <div class="header-body">
            <div class="row align-items-center">
                <div class="col">
                    <h6 class="header-pretitle">Cursos</h6>
                    <h1 class="header-title">{{ $name }}</h1>
                </div>
            </div>

            <div class="row align-items-center">
                <div class="col">
                    <ul class="nav nav-tabs nav-overflow header-tabs">
                        <li class="nav-item">
                            <a href="{{ route('course.show', ['url' => $id]) }}" class="nav-link">Turmas</a>
                        </li>
                        <li class="nav-item">
                            <a href="" class="nav-link">Certificados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/courses/home.blade.php
@extends('layouts.institution')

@section('content')

@component('institution.header')
@endcomponent

<div class="container">
    <div class="row">
        <div class="col-12">

            @if(session('status'))
                @component('institution.notification')
                    @slot('message')
                        {{session('status')}}
                    @endslot
                @endcomponent
            @endif

            <div class="card" data-toggle="lists" data-options="{&quot;valueNames&quot;: [&quot;name&quot;]}">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="card-header-title">Cursos</h3>
                        </div>

                        <div class="col-auto">
                            <a href="{{route('course.create')}}" class="btn btn-sm btn-primary gc-btn-new">
                                <i class="fe fe-plus"></i> Novo curso
                            </a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    <ul class="list-group list-group-lg list-group-flush list my-n4">
                        @foreach($courses as $course)
                        <li class="list-group-item px-0">
                            <div class="row align-items-center">
                                <div class="col-auto">
                                    <a href="#!" class="avatar avatar-lg">
                                        <span class="avatar-title rounded bg-white text-secondary">
                                            <span class="fe fe-book"></span>
                                        </span>
                                    </a>
                                </div>

                                <div class="col ml-n2">
                                    <h4 class="card-title mb-1 name"><a href="#!">{{ $course->name }}</a></h4>
                                    <p class="card-text small text-muted mb-1">
                                        Coordenador: {{ $course->coordinator }}
                                    </p>
                                    <p class="card-text small text-muted">
                                        Adicionado em {{ $course->created_at->format('d/m/Y') }}
                                    </p>
                                </div>

                                <div class="col-auto">
                                    <a href="{{ route('course.show', ['id' => $course->id]) }}" class="btn btn-sm btn-white gc-btn-new d-none d-md-inline-block">
                                        Acessar
                                    </a>
                                </div>

                                <div class="col-auto">
                                    <div class="dropdown">
                                        <a href="#" class="dropdown-ellipses dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fe fe-more-vertical"></i>
                                        </a>

                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a href="{{ route('course.edit', ['id' => $course->id]) }}" class="dropdown-item">
                                                <i class="fe fe-edit gc-mr-5"></i> Editar
                                            </a>
                                            <hr class="my-2">
                                            <form action="{{ route('course.destroy', ['id' => $course->id]) }}" method="post">
                                                @csrf
                                                {{ method_field('DELETE') }}
                                                <button class="btn btn-link dropdown-item">
                                                    <i class="fe fe-trash-2 gc-mr-5"></i> Excluir
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        @endforeach
                    </ul>
                </div>

            </div>
        </div>
    </div>

</div>

@endsection

resources/views/courses/show.blade.php
@extends('layouts.institution')

@section('content')

@component('courses.header')
    @slot('id') {{$course->id}} @endslot
    @slot('name') {{$course->name}} @endslot
@endcomponent

<div class="container">
    <div class="row">
        <div class="col-12">

            @if(session('status'))
            @component('institution.notification')
            @slot('message')
            {{session('status')}}
            @endslot
            @endcomponent
            @endif

            <div class="card" data-toggle="lists" data-options="{&quot;valueNames&quot;: [&quot;name&quot;]}">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="card-header-title">Turmas</h3>
                        </div>

                        <div class="col-auto">
                            <a href="{{ route('classes.create', ['url' => $course->url]) }}" class="btn btn-sm btn-primary gc-btn-new">
                                <i class="fe fe-plus"></i> Nova turma
                            </a>
                        </div>
                    </div>
                </div>

                <div class="table-responsive mb-0">
                    <table class="table table-sm table-nowrap card-table">
                        <thead>
                            <tr>
                                <th>Nome</th>
                                <th class="text-center">Data de cadastro</th>
                                <th class="text-center">Ações</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($classes as $class)
                            <tr>
                                <td class="align-middle">{{ $class->name }}</td>
                                <td class="align-middle text-center">{{ $class->created_at->format('d/m/Y') }}</td>
                                <td class="align-middle text-center">
                                    <a href="{{ route('classes.show', ['url' => $course->url, 'class' => $class->url]) }}" class="btn btn-sm btn-white gc-btn-new d-none d-md-inline-block">
                                        Acessar
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection